version: "3.3"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #opcional
    volumes:
      - /home/vagrant/jellyfin/multimedia/library:/config
      - /home/vagrant/jellyfin/multimedia/tvseries:/data/tvshows
      - /home/vagrant/jellyfin/multimedia/movies:/data/movies
      - /home/vagrant/jellyfin/multimedia/images:/data/images
    ports:
      - 8096:8096
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #opcional
      - USER=Dockplay
      - PASS=Dockplay
    volumes:
      - /home/vagrant/jellyfin/multimedia/library:/config
      - /home/vagrant/jellyfin/multimedia/movies:/downloads
      - /home/vagrant/jellyfin/multimedia/tvseries:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HfPM9H8Xhp
      MYSQL_DATABASE: dockplaydb
      MYSQL_USER: yeinel
      MYSQL_PASSWORD: HfPM9H8Xhp

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: yeinel
      WORDPRESS_DB_PASSWORD: HfPM9H8Xhp
      WORDPRESS_DB_NAME: dockplaydb
volumes:
    db_data: {}
